# HTTP
quarkus.http.port=6868


# SECURITY / HEALTH

quarkus.http.auth.permission.health.paths=/q/health/*
quarkus.http.auth.permission.health.policy=permit

quarkus.http.auth.permission.public.paths=/q/health/*
quarkus.http.auth.permission.public.policy=permit

# Public image endpoints (no auth required)
quarkus.http.auth.permission.public-image-download.paths=/image/download/*
quarkus.http.auth.permission.public-image-download.policy=permit
#quarkus.http.auth.permission.public-image-download.auth-mechanism=none

quarkus.http.auth.permission.public-image-property.paths=/image/property/*
quarkus.http.auth.permission.public-image-property.policy=permit
#quarkus.http.auth.permission.public-image-property.auth-mechanism=none

# Protect all other endpoints
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# OIDC (service)
quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL}
quarkus.oidc.client-id=${QUARKUS_OIDC_CLIENT_ID}
quarkus.oidc.application-type=service
# remove in production!!! TLS verification is disabled
%dev.quarkus.oidc.tls.verification=none
%dev.quarkus.oidc-client.tls.verification=none

# OIDC client (if you call other services)
quarkus.oidc-client.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL}
quarkus.oidc-client.client-id=${QUARKUS_OIDC_CLIENT_CLIENT_ID}
quarkus.oidc-client.credentials.secret=${QUARKUS_OIDC_CLIENT_SECRET}
quarkus.oidc-client.grant.type=client

# Rest Client configuration for calling other services
quarkus.rest-client.image-classification.url=${IMAGE_CLASSIFICATION_URL}
quarkus.rest-client.image-classification.connect-timeout=5000
quarkus.rest-client.image-classification.read-timeout=15000

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_JDBC_URL}

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.connect-retries=10
quarkus.flyway.connect-retries-interval=5s

#%dev.quarkus.flyway.clean-at-start=false

# Google Cloud Storage
gcs.project-id=${GCP_PROJECT_ID}
gcs.private-bucket-name=${GCP_PRIVATE_BUCKET}
gcs.public-bucket-name=${GCP_PUBLIC_BUCKET}
gcs.service-account-email=${GCP_SERVICE_ACCOUNT}

# Container image (optional)
quarkus.container-image.build=true
quarkus.container-image.name=files
quarkus.container-image.tag=latest

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=${QUARKUS_CORS_ORIGIN_URL:http://localhost:4200,https://myproperty-essa.com}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,origin,x-requested-with
quarkus.http.cors.exposed-headers=authorization
quarkus.http.cors.access-control-allow-credentials=true