apiVersion: v1
kind: Service
metadata:
  name: files-internal-loadbalancer
  namespace: essa-project
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.files.deployment.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.files.deployment.image.containerPort }}