apiVersion: v1
kind: ServiceAccount
metadata:
  name: files-service-ksa
  namespace: essa-project
  annotations:
    iam.gke.io/gcp-service-account: file-service@artful-reactor-351917.iam.gserviceaccount.com
